### ISSUE TITLE
Parser is unable to parse large Gtk GIR file in a timely manner

### ISSUE THREAD

**Issue by demizer** [hungrybluedev/xml#3]
The Gtk GIR file is a large xml file that describes how to programmatically create language bindings to Gtk.

On arch this file is located here:

```
❯ pacman -Qo /usr/share/gir-1.0/Gtk-4.0.gir
/usr/share/gir-1.0/Gtk-4.0.gir is owned by gtk4 1:4.12.0-2
```
After implementing changes in https://github.com/demizer/xml/tree/gtk-gir-fixes the parser takes a very long time to parse the file (it never finished for me). It seems the parser is incrementing character by character which might be contributing to its slowness.

I know it is still early days for this effort but it might be worthwhile checking it out.

Thanks!

**Comment by hungrybluedev** [comment]
Thanks for the issue.

Can you share the file here? Or add it to a directory in the local spec (follow the pattern as the rest of the examples).

I used the string return in order to eventually replace it with a Reader interface. It seems that change needs to be applied now!

I'll get started on this today. Once you upload the test XML file to the spec, I'll be able to test the new implementation and hopefully improve the performance/outcome.

**Comment by hungrybluedev** [comment]
@demizer Can you confirm if [this](https://github.com/gtk-rs/gir-files/blob/master/Gtk-4.0.gir) is similar to what you are parsing?

**Comment by hungrybluedev** [comment]
I've started work on migrating from strings to using the `io.Reader` interface. Today's progress: started work on the Prolog parsing function.

The work is tedious, so I will take a few breaks and continue tomorrow.

**Comment by demizer** [comment]
> @demizer Can you confirm if [this](https://github.com/gtk-rs/gir-files/blob/master/Gtk-4.0.gir) is similar to what you are parsing?

That's it! Thank you!

**Comment by hungrybluedev** [comment]
I've refactored the module to use the io.Reader interface now. Will now test with the big file.

**Comment by hungrybluedev** [comment]
@demizer UPDATE:

I've updated the attribute parsing (which was failing due to there being spaces inside the quoted values like `key="const char*"`).

The main example now shows that the file is being parsed properly and the output is generated as expected. Let me know if this works. Without `-prod`, it takes around ~3 seconds but with `-prod` is it faster.

If you think this works, let me know and I'll mark this issue as resolved.

**Comment by hungrybluedev** [comment]
If you have the time, can you please contribute a unit test with a decent number of assertions for the GTK file test [here](https://github.com/hungrybluedev/xml/blob/main/test/gtk/gtk_test.v)?

**Comment by demizer** [comment]
Thanks! Will test in a day or two and contribute some tests.

**Comment by hungrybluedev** [comment]
@demizer Hey! Were you able to find time to test the new implementation? Did it meet your expectations?

**Comment by demizer** [comment]
Works great! Thanks!
